### ISSUE TITLE
Unautharized error in jobman images 

### ISSUE THREAD

**Issue by sophiasw** [chaimeleon-eu/jobman#11]
jobman images and jobman image-details -i [image-name] return "Unable to load repositories from [harbor -link] [ERROR]: Unauthorized"

This error did not occur the last time I used it on 26/05/2023.

**Comment by asalic** [comment]
@sophiasw Can you please re-deploy the desktop (delete the one that you have right now and create a new one through kube apps) and test again?

**Comment by sophiasw** [comment]
Yes, it works again!

**Comment by asalic** [comment]
@sophiasw all right, thanks for trying it out :)
