### ISSUE TITLE
table from jobman images deformatted

### ISSUE THREAD

**Issue by sophiasw** [chaimeleon-eu/jobman#14]
The table that is shown in jupyter when executing !jobman images is deformatted (see image).

<img width="1247" alt="Bildschirmfoto 2023-06-27 um 13 02 38" src="https://github.com/chaimeleon-eu/jobman/assets/28859189/fa7fd20c-ef7e-480d-9b91-62841635914d">

**Comment by asalic** [comment]
@sophiasw Would an option to generate a json output help you?

**Comment by sophiasw** [comment]
I don't think this is necessary. It seems the table width does not match the screen width and when the screen is to small, the right end of the table overflows and is overlayed with the left side. I think this issue would be solved if the Tags List would have two rows to list the tags, then it would only extend to a second row within the right column rather than to the left side of the table. 
If this is not easily done, it can also stay like this - it's just a cosmetic error.

**Comment by sophiasw** [comment]
Would it be an option to give the table a fixed but smaller size that will fit most terminals? Maybe the entries with a long list of tags can receive an extra row that is empty in the Image Name column?

My guess is that users will only very briefly look at this table and wouldn't want to interact with it more. The information is all there and readable, so it should be fine either way.

**Comment by asalic** [comment]
I could go old school and make it 80 cols wide, default. Is that all right for you?

**Comment by sophiasw** [comment]
Sounds good to me.
